/* Generated By:JavaCC: Do not edit this line. CalcConstants.java */
package Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int CONSTANT = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"%\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
